LostGamer/LostGamer/Models/UserProfiles.cs
using System;
using System.Collections.Generic;

namespace LostGamer.Models
{
    public partial class UserProfiles
    {
        public UserProfiles()
        {
            Comments = new HashSet<Comments>();
            Guides = new HashSet<Guides>();
            UserComments = new HashSet<UserComments>();
            UserGuidesColletion = new HashSet<UserGuidesColletion>();
            UserReviews = new HashSet<UserReviews>();
        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public DateTime? DateCreated { get; set; }
        public int? UserTypeId { get; set; }
        public string UserAccountId { get; set; }

        public UserType UserType { get; set; }
        public ICollection<Comments> Comments { get; set; }
        public ICollection<Guides> Guides { get; set; }
        public ICollection<UserComments> UserComments { get; set; }
        public ICollection<UserGuidesColletion> UserGuidesColletion { get; set; }
        public ICollection<UserReviews> UserReviews { get; set; }
    }
}

LostGamer/LostGamer/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LostGamer.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace LostGamer.Controllers
{
    public class GamesController : Controller
    {
        private readonly LostGamerContext _context;
        private UserManager<IdentityUser> _userManager;
        private IHostingEnvironment _webroot;

        public GamesController(LostGamerContext context, UserManager<IdentityUser> userManager, IHostingEnvironment webroot)
        {
            _context = context;
            _userManager = userManager;
            _webroot = webroot;
        }

        // GET: Games
        public async Task<IActionResult> Index()
        {
            var lostGamerContext = _context.Games.Include(g => g.Category).Include(g => g.Company).Include(g => g.Platforms).Include(g => g.Rating);
            return View(await lostGamerContext.ToListAsync());
        }

        // copy Index relable GameLibrary 
        public async Task<IActionResult> GameLibrary()
        {
            var lostGamerContext = _context.Games.Include(g => g.Category).Include(g => g.Company).Include(g => g.Platforms).Include(g => g.Rating);
            return View(await lostGamerContext.ToListAsync());
        }

        // GET: Games/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var games = await _context.Games
                .Include(g => g.Category)
                .Include(g => g.Company)
                .Include(g => g.Platforms)
                .Include(g => g.Rating)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (games == null)
            {
                return NotFound();
            }

            return View(games);
        }

        // Copy Details, paste then Relable Show now GET: Games/Show/5
        public async Task<IActionResult> Show(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var games = await _context.Games
                .Include(g => g.Category)
                .Include(g => g.Company)
                .Include(g => g.Platforms)
                .Include(g => g.Rating)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (games == null)
            {
                return NotFound();
            }

            return View(games);
        }

        // GET: Games/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Category");
            ViewData["CompanyId"] = new SelectList(_context.Company, "Id", "CompanyName");
            ViewData["PlatformsId"] = new SelectList(_context.Platforms, "Id", "PlatformName");
            ViewData["RatingId"] = new SelectList(_context.Rating, "Id", "RatingNum");
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,GameTitle,PlatformsId,CategoryId,RatingId,Synopsis,CompanyId")] Games games,
            IFormFile FilePhoto)
        {
            if (FilePhoto.Length > 0)
            {
                string coverLogo = _webroot.WebRootPath + "\\gamePhotos\\";
                var fileName = Path.GetFileName(FilePhoto.FileName);
                
                using (var stream = System.IO.File.Create(coverLogo + fileName))
                {
                    await FilePhoto.CopyToAsync(stream);
                    games.CoverLogo = fileName;
                }
            }
            if (ModelState.IsValid)
            {
                _context.Add(games);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Category", games.CategoryId);
            ViewData["CompanyId"] = new SelectList(_context.Company, "Id", "CompanyName", games.CompanyId);
            ViewData["PlatformsId"] = new SelectList(_context.Platforms, "Id", "PlatformName", games.PlatformsId);
            ViewData["RatingId"] = new SelectList(_context.Rating, "Id", "RatingNum", games.RatingId);
            return View(games);
        }

        // GET: Games/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var games = await _context.Games.FindAsync(id);
            if (games == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Category", games.CategoryId);
            ViewData["CompanyId"] = new SelectList(_context.Company, "Id", "CompanyName", games.CompanyId);
            ViewData["PlatformsId"] = new SelectList(_context.Platforms, "Id", "PlatformName", games.PlatformsId);
            ViewData["RatingId"] = new SelectList(_context.Rating, "Id", "RatingNum", games.RatingId);
            return View(games);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,GameTitle,PlatformsId,CategoryId,RatingId,Synopsis,CompanyId")] Games games,
            IFormFile FilePhoto)
        {
            if (id != games.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(games);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GamesExists(games.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Category", games.CategoryId);
            ViewData["CompanyId"] = new SelectList(_context.Company, "Id", "CompanyName", games.CompanyId);
            ViewData["PlatformsId"] = new SelectList(_context.Platforms, "Id", "PlatformName", games.PlatformsId);
            ViewData["RatingId"] = new SelectList(_context.Rating, "Id", "RatingNum", games.RatingId);
            return View(games);
        }

        // GET: Games/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var games = await _context.Games
                .Include(g => g.Category)
                .Include(g => g.Company)
                .Include(g => g.Platforms)
                .Include(g => g.Rating)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (games == null)
            {
                return NotFound();
            }

            return View(games);
        }

        // POST: Games/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var games = await _context.Games.FindAsync(id);
            _context.Games.Remove(games);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GamesExists(int id)
        {
            return _context.Games.Any(e => e.Id == id);
        }
    }
}

LostGamer/LostGamer/Controllers/GuidesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LostGamer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using LostGamer.ViewModels;

namespace LostGamer.Controllers
{
    public class GuidesController : Controller
    {
        private readonly LostGamerContext _context;
        private UserManager<IdentityUser> _userManager;

        public GuidesController(LostGamerContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Guides
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var lostGamerContext = _context.Guides.Include(g => g.Game).Include(g => g.UserProfiles);
            return View(await lostGamerContext.ToListAsync());
        }
        //copy Index, paste then relable UserGuides.
        public async Task<IActionResult> UserGuides(int? id)
        {
            var lostGamerContext = _context.Guides.Where(g => g.UserProfilesId == id).Include(g => g.Game).Include(g => g.UserProfiles);
            return View(await lostGamerContext.ToListAsync());
        }

        //copy Index, paste then relable GamesGuides.
        public async Task<IActionResult> GamesGuides(int? id)
        {

            var lostGamerContext = _context.Guides.Where(g => g.GameId == id).Include(g => g.Game).Include(g => g.UserProfiles);
            //var lostGamerContext = _context.Guides.Include(g => g.Game.Id == id).Include(g => g.UserProfiles);
            return View(await lostGamerContext.ToListAsync());
        }

        // GET: Guides/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guides = await _context.Guides
                .Include(g => g.Game)
                .Include(g => g.UserProfiles)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (guides == null)
            {
                return NotFound();
            }

            return View(guides);
        }

        //copy Details, paste then relable Guide
        public async Task<IActionResult> Guide(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guides = await _context.Guides
                .Include(g => g.Game)
                .Include(g => g.UserProfiles)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (guides == null)
            {
                return NotFound();
            }

            return View(guides);
        }

        // GET: Guides/Create
        [Authorize]
        public IActionResult Create(int id)
        {
            string userID = _userManager.GetUserId(User);
            UserProfiles profile = _context.UserProfiles.FirstOrDefault(p => p.UserAccountId == userID);
            ViewData["GameId"] = new SelectList(_context.Games, "Id", "GameTitle");
            ViewBag.UserProfileId = profile.Id;
            return View();
        }

        // POST: Guides/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GuideTitle,GuideContent,DateSubmitted,LastUpdated,UserProfilesId,GameId")] Guides guides)
        {
            if (ModelState.IsValid)
            {
                _context.Add(guides);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Guide));
            }
            ViewData["GameId"] = new SelectList(_context.Games, "Id", "GameTitle", guides.GameId);
            //ViewData["UserProfilesId"] = new SelectList(_context.UserProfiles, "Id", "DisplayName", guides.UserProfilesId);
            return View(guides);
        }

        // GET: Guides/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guides = await _context.Guides.FindAsync(id);
            if (guides == null)
            {
                return NotFound();
            }
            ViewData["GameId"] = new SelectList(_context.Games, "Id", "GameTitle", guides.GameId);
            //ViewData["UserProfilesId"] = new SelectList(_context.UserProfiles, "Id", "DisplayName", guides.UserProfilesId);
            return View(guides);
        }

        // POST: Guides/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GuideTitle,GuideContent,DateSubmitted,LastUpdated,UserProfilesId,GameId")] Guides guides)
        {
            if (id != guides.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(guides);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GuidesExists(guides.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameId"] = new SelectList(_context.Games, "Id", "GameTitle", guides.GameId);
            //ViewData["UserProfilesId"] = new SelectList(_context.UserProfiles, "Id", "DisplayName", guides.UserProfilesId);
            return View(guides);
        }

        // GET: Guides/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guides = await _context.Guides
                .Include(g => g.Game)
                .Include(g => g.UserProfiles)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (guides == null)
            {
                return NotFound();
            }

            return View(guides);
        }

        // POST: Guides/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var guides = await _context.Guides.FindAsync(id);
            _context.Guides.Remove(guides);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GuidesExists(int id)
        {
            return _context.Guides.Any(e => e.Id == id);
        }
    }
}

LostGamer/LostGamer/Views/UserProfiles/Create.cshtml
@using Microsoft.AspNetCore.Identity;
@inject UserManager<IdentityUser> userManager
@model LostGamer.Models.UserProfiles

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>UserProfiles</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DisplayName" class="control-label"></label>
                <input asp-for="DisplayName" class="form-control" />
                <span asp-validation-for="DisplayName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserTypeId" class="control-label"></label>
                <select asp-for="UserTypeId" class ="form-control" asp-items="ViewBag.UserTypeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="UserAccountId" class="control-label"></label>
                <input asp-for="UserAccountId" class="form-control" value="@userManager.GetUserId(User)" />
                <span asp-validation-for="UserAccountId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LostGamer/LostGamer/Views/UserProfiles/Delete.cshtml
@model LostGamer.Models.UserProfiles

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserProfiles</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DisplayName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DisplayName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserAccountId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserAccountId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserType.TypeName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LostGamer/LostGamer/Views/UserProfiles/Details.cshtml
@model LostGamer.Models.UserProfiles

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>UserProfiles</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DisplayName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DisplayName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserAccountId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserAccountId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserType.TypeName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

LostGamer/LostGamer/Views/UserProfiles/Edit.cshtml
@model LostGamer.Models.UserProfiles

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>UserProfiles</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DisplayName" class="control-label"></label>
                <input asp-for="DisplayName" class="form-control" />
                <span asp-validation-for="DisplayName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateCreated" class="control-label"></label>
                <input asp-for="DateCreated" class="form-control" />
                <span asp-validation-for="DateCreated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserTypeId" class="control-label"></label>
                <select asp-for="UserTypeId" class="form-control" asp-items="ViewBag.UserTypeId"></select>
                <span asp-validation-for="UserTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserAccountId" class="control-label"></label>
                <input asp-for="UserAccountId" class="form-control" />
                <span asp-validation-for="UserAccountId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LostGamer/LostGamer/Views/UserProfiles/ProfileInfo.cshtml
@model LostGamer.Models.UserProfiles

@{
    ViewData["Title"] = "ProfileInfo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ProfileInfo</h2>

<div>
    <h4>UserProfiles</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DisplayName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DisplayName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class="hidden">
            @Html.DisplayNameFor(model => model.UserAccountId)
        </dt>
        <dd class="hidden">
            @Html.DisplayFor(model => model.UserAccountId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserType.TypeName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="EditProfile" asp-route-id="@Model.Id" type="button" class="btn btn-success">Edit Profile</a> |
    <a asp-controller="Games" asp-action="GameLibrary" type="button" class="btn btn-success">List of Games</a> |
    <a asp-controller="Guides" asp-action="UserGuides" asp-route-id="@Model.Id" type="button" class="btn btn-success">User Guides<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-text" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path d="M4 0h5.5v1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4.5h1V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2z" />
    <path d="M9.5 3V0L14 4.5h-3A1.5 1.5 0 0 1 9.5 3z" />
    <path fill-rule="evenodd" d="M5 11.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5zm0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z" />
</svg></a> |
    <a asp-controller="Comments" asp-action="UserComments" asp-route-id="@Model.Id" type="button" class="btn btn-success">User Comments<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chat-text" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z" />
    <path fill-rule="evenodd" d="M4 5.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zM4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8zm0 2.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5z" />
</svg></a> |
</div>