LostGamer/LostGamer/Models/Comments.cs
using System;
using System.Collections.Generic;

namespace LostGamer.Models
{
    public partial class Comments
    {
        public Comments()
        {
            UserComments = new HashSet<UserComments>();
        }

        public int Id { get; set; }
        public string Comment { get; set; }
        public DateTime? DatePosted { get; set; }
        public int? UserProfilesId { get; set; }
        public int? GuideId { get; set; }

        public Guides Guides { get; set; }
        public UserProfiles UserProfiles { get; set; }
        public ICollection<UserComments> UserComments { get; set; }
    }
}

LostGamer/LostGamer/Models/UserComments.cs
using System;
using System.Collections.Generic;

namespace LostGamer.Models
{
    public partial class UserComments
    {
        public int Id { get; set; }
        public int? UserProfilesId { get; set; }
        public int? CommentId { get; set; }

        public Comments Comment { get; set; }
        public UserProfiles UserProfiles { get; set; }
    }
}

LostGamer/LostGamer/Controllers/GuidesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LostGamer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using LostGamer.ViewModels;

namespace LostGamer.Controllers
{
    public class GuidesController : Controller
    {
        private readonly LostGamerContext _context;
        private UserManager<IdentityUser> _userManager;

        public GuidesController(LostGamerContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Guides
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var lostGamerContext = _context.Guides.Include(g => g.Game).Include(g => g.UserProfiles);
            return View(await lostGamerContext.ToListAsync());
        }
        //copy Index, paste then relable UserGuides.
        public async Task<IActionResult> UserGuides(int? id)
        {
            var lostGamerContext = _context.Guides.Where(g => g.UserProfilesId == id).Include(g => g.Game).Include(g => g.UserProfiles);
            return View(await lostGamerContext.ToListAsync());
        }

        //copy Index, paste then relable GamesGuides.
        public async Task<IActionResult> GamesGuides(int? id)
        {

            var lostGamerContext = _context.Guides.Where(g => g.GameId == id).Include(g => g.Game).Include(g => g.UserProfiles);
            //var lostGamerContext = _context.Guides.Include(g => g.Game.Id == id).Include(g => g.UserProfiles);
            return View(await lostGamerContext.ToListAsync());
        }

        // GET: Guides/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guides = await _context.Guides
                .Include(g => g.Game)
                .Include(g => g.UserProfiles)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (guides == null)
            {
                return NotFound();
            }

            return View(guides);
        }

        //copy Details, paste then relable Guide
        public async Task<IActionResult> Guide(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guides = await _context.Guides
                .Include(g => g.Game)
                .Include(g => g.UserProfiles)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (guides == null)
            {
                return NotFound();
            }

            return View(guides);
        }

        // GET: Guides/Create
        [Authorize]
        public IActionResult Create(int id)
        {
            string userID = _userManager.GetUserId(User);
            UserProfiles profile = _context.UserProfiles.FirstOrDefault(p => p.UserAccountId == userID);
            ViewData["GameId"] = new SelectList(_context.Games, "Id", "GameTitle");
            ViewBag.UserProfileId = profile.Id;
            return View();
        }

        // POST: Guides/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GuideTitle,GuideContent,DateSubmitted,LastUpdated,UserProfilesId,GameId")] Guides guides)
        {
            if (ModelState.IsValid)
            {
                _context.Add(guides);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Guide));
            }
            ViewData["GameId"] = new SelectList(_context.Games, "Id", "GameTitle", guides.GameId);
            //ViewData["UserProfilesId"] = new SelectList(_context.UserProfiles, "Id", "DisplayName", guides.UserProfilesId);
            return View(guides);
        }

        // GET: Guides/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guides = await _context.Guides.FindAsync(id);
            if (guides == null)
            {
                return NotFound();
            }
            ViewData["GameId"] = new SelectList(_context.Games, "Id", "GameTitle", guides.GameId);
            //ViewData["UserProfilesId"] = new SelectList(_context.UserProfiles, "Id", "DisplayName", guides.UserProfilesId);
            return View(guides);
        }

        // POST: Guides/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GuideTitle,GuideContent,DateSubmitted,LastUpdated,UserProfilesId,GameId")] Guides guides)
        {
            if (id != guides.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(guides);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GuidesExists(guides.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameId"] = new SelectList(_context.Games, "Id", "GameTitle", guides.GameId);
            //ViewData["UserProfilesId"] = new SelectList(_context.UserProfiles, "Id", "DisplayName", guides.UserProfilesId);
            return View(guides);
        }

        // GET: Guides/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guides = await _context.Guides
                .Include(g => g.Game)
                .Include(g => g.UserProfiles)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (guides == null)
            {
                return NotFound();
            }

            return View(guides);
        }

        // POST: Guides/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var guides = await _context.Guides.FindAsync(id);
            _context.Guides.Remove(guides);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GuidesExists(int id)
        {
            return _context.Guides.Any(e => e.Id == id);
        }
    }
}

LostGamer/LostGamer/Controllers/UserProfilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LostGamer.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace LostGamer.Controllers
{
    public class UserProfilesController : Controller
    {
        private readonly LostGamerContext _context;
        private UserManager<IdentityUser> _userManager;

        public UserProfilesController(LostGamerContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: UserProfiles
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index()
        {
            var lostGamerContext = _context.UserProfiles.Include(u => u.UserType);
            return View(await lostGamerContext.ToListAsync());
        }

        // GET: UserProfiles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userProfiles = await _context.UserProfiles
                .Include(u => u.UserType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userProfiles == null)
            {
                return NotFound();
            }

            return View(userProfiles);
        }

        // GET: UserProfiles/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["UserTypeId"] = new SelectList(_context.UserType, "Id", "TypeName");
            return View();
        }

        public IActionResult ProfileInfo()
        {
            string userID = _userManager.GetUserId(User);
            UserProfiles profile = _context.UserProfiles.Include(u => u.UserType).FirstOrDefault(p => p.UserAccountId == userID);

            if (profile == null)
            {
                return RedirectToAction("Create");
            }

            return View(profile);

        }

        // POST: UserProfiles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,DisplayName,DateCreated,UserTypeId,UserAccountId")] UserProfiles userProfiles)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userProfiles);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ProfileInfo));
            }
            ViewData["UserTypeId"] = new SelectList(_context.UserType, "Id", "TypeName", userProfiles.UserTypeId);
            return View(userProfiles);
        }

        // GET: UserProfiles/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userProfiles = await _context.UserProfiles.FindAsync(id);
            if (userProfiles == null)
            {
                return NotFound();
            }
            ViewData["UserTypeId"] = new SelectList(_context.UserType, "Id", "TypeName", userProfiles.UserTypeId);
            return View(userProfiles);
        }

        [Authorize]
        public async Task<IActionResult> EditProfile(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userProfiles = await _context.UserProfiles.FindAsync(id);
            if (userProfiles == null)
            {
                return NotFound();
            }
            ViewData["UserTypeId"] = new SelectList(_context.UserType, "Id", "TypeName", userProfiles.UserTypeId);
            return View(userProfiles);
        }

        // POST: UserProfiles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,DisplayName,DateCreated,UserTypeId,UserAccountId")] UserProfiles userProfiles)
        {
            if (id != userProfiles.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userProfiles);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserProfilesExists(userProfiles.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserTypeId"] = new SelectList(_context.UserType, "Id", "TypeName", userProfiles.UserTypeId);
            return View(userProfiles);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditProfile(int id, [Bind("Id,FirstName,LastName,DisplayName,DateCreated,UserTypeId,UserAccountId")] UserProfiles userProfiles)
        {
            if (id != userProfiles.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userProfiles);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserProfilesExists(userProfiles.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserTypeId"] = new SelectList(_context.UserType, "Id", "TypeName", userProfiles.UserTypeId);
            return View(userProfiles);
        }

        // GET: UserProfiles/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userProfiles = await _context.UserProfiles
                .Include(u => u.UserType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userProfiles == null)
            {
                return NotFound();
            }

            return View(userProfiles);
        }

        // POST: UserProfiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userProfiles = await _context.UserProfiles.FindAsync(id);
            _context.UserProfiles.Remove(userProfiles);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserProfilesExists(int id)
        {
            return _context.UserProfiles.Any(e => e.Id == id);
        }
    }
}

LostGamer/LostGamer/Views/Comments/Create.cshtml
@using Microsoft.AspNetCore.Identity;
@model LostGamer.Models.Comments
@inject Microsoft.AspNetCore.Identity.UserManager<IdentityUser> userManager
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>Comments</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <textarea asp-for="Comment" class="form-control" typeof="textarea" rows="5">Enter Comment</textarea>
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserProfilesId" class="control-label"></label>
                <input asp-for="UserProfilesId" class="form-control" value="@ViewBag.UserProfileId" />
            </div>
            <div class="form-group">
                <label asp-for="GuideId" class="control-label"></label>
                <input asp-for="GuideId" class="form-control" value="@ViewBag.GuideId" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ViewComments">Back to Comments</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LostGamer/LostGamer/Views/Comments/Delete.cshtml
@model LostGamer.Models.Comments

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Comments</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DatePosted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DatePosted)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserProfiles)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserProfiles.DisplayName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LostGamer/LostGamer/Views/Comments/Details.cshtml
@model LostGamer.Models.Comments

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Comments</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DatePosted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DatePosted)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserProfiles)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserProfiles.DisplayName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Guides)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Guides.GuideTitle)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="ViewComments" asp-route-id="@Model.GuideId">Back to Comments</a>|
    <a asp-controller="Guides" asp-action="Guide" asp-route-id="@Model.GuideId">Back to Guide</a>|
</div>

LostGamer/LostGamer/Views/Comments/Edit.cshtml
@model LostGamer.Models.Comments

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>Comments</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <input asp-for="Comment" class="form-control" />
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatePosted" class="control-label"></label>
                <input asp-for="DatePosted" class="form-control" />
                <span asp-validation-for="DatePosted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserProfilesId" class="control-label"></label>
                <select asp-for="UserProfilesId" class="form-control" asp-items="ViewBag.UserProfilesId"></select>
                <span asp-validation-for="UserProfilesId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LostGamer/LostGamer/Views/Comments/Index.cshtml
@model IEnumerable<LostGamer.Models.Comments>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Comment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatePosted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserProfiles)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Guides)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatePosted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserProfiles.DisplayName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Guides.GuideTitle)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

LostGamer/LostGamer/Views/Comments/UserComments.cshtml
@model IEnumerable<LostGamer.Models.Comments>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    <a asp-controller="UserProfiles" asp-action="ProfileInfo" >Back to Profile</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Comment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatePosted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserProfiles)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Guides)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatePosted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserProfiles.DisplayName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Guides.GuideTitle)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
            </td>
        </tr>
}
    </tbody>
</table>

LostGamer/LostGamer/Views/Comments/ViewComments.cshtml
@model IEnumerable<LostGamer.Models.Comments>
@{
    ViewData["Title"] = "Guide Comments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Guide Comments</h2>

<p>

</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Comment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatePosted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserProfiles)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Guides)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatePosted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserProfiles.DisplayName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Guides.GuideTitle)
            </td>
            <td>
                |<a asp-action="Details" asp-route-id="@item.Id">View</a> |
            </td>
        </tr>
}
    </tbody>
</table>